# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
sudo: required
julia:
  - release
#  - nightly

notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("OpenMPIData"); Pkg.test("OpenMPIData"; coverage=true)'
before_install:
  - julia -e 'Pkg.update()'
  #- test "x$TRAVIS_OS_NAME" = xosx -o "x$PYTHON" = xConda-python || (sudo apt-get -qq update && sudo apt-get install -y $PYTHON)
  # Work around (part 1/2) matplotlib backend error leading to "matplotlib.pyplot could not be found by pyimport": can't just set env PYTHON="".
  - julia -e 'ENV["PYTHON"]=""; Pkg.add("Conda"); using Conda; Conda.update(); Conda.add("matplotlib"); Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot");'
after_success:
  # push coverage results to Coveralls
  #- export LD_LIBRARY_PATH=$HOME/.julia/v0.6/Conda/deps/usr/lib julia -e 'cd(Pkg.dir("OpenMPIData")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  #- export LD_LIBRARY_PATH=$HOME/.julia/v0.6/Conda/deps/usr/lib julia -e 'cd(Pkg.dir("OpenMPIData")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - export LD_LIBRARY_PATH=$HOME/.julia/v0.6/Conda/deps/usr/lib julia -e 'cd(Pkg.dir("OpenMPIData")); ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath("docs", "make.jl"))'
